import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VoiceNote from "../components/voice-note";
import VoiceNoteList from "../components/voice-note-list";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="bg-neutral-800 text-white fixed inset-0">
            <body className={`${inter.className} flex min-h-screen items-center`}>
                <VoiceNoteList/>

                <main className="flex-auto">
                    {children}
                </main>
            </body>
        </html>
    );
}
